/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as DeploymentRouteImport } from './routes/deployment'
import { Route as EventsRouteImport } from './routes/events'
import { Route as MapRouteImport } from './routes/map'
import { Route as PostureRouteImport } from './routes/posture'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as ThresholdsRouteImport } from './routes/thresholds'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as AuthCallbackRouteImport } from './routes/auth_.callback'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppAlertsRouteImport } from './routes/_authenticated/app.alerts'
import { Route as AuthenticatedAppAssetsRouteImport } from './routes/_authenticated/app.assets'
import { Route as AuthenticatedAppCopilotRouteImport } from './routes/_authenticated/app.copilot'
import { Route as AuthenticatedAppDeploymentRouteImport } from './routes/_authenticated/app.deployment'
import { Route as AuthenticatedAppEventsRouteImport } from './routes/_authenticated/app.events'
import { Route as AuthenticatedAppMapRouteImport } from './routes/_authenticated/app.map'
import { Route as AuthenticatedAppPostureRouteImport } from './routes/_authenticated/app.posture'
import { Route as AuthenticatedAppRiskRouteImport } from './routes/_authenticated/app.risk'
import { Route as AuthenticatedAppThresholdsRouteImport } from './routes/_authenticated/app.thresholds'
import { Route as AuthenticatedAppTimelineRouteImport } from './routes/_authenticated/app.timeline'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentRoute = DeploymentRouteImport.update({
  id: '/deployment',
  path: '/deployment',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const PostureRoute = PostureRouteImport.update({
  id: '/posture',
  path: '/posture',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const ThresholdsRoute = ThresholdsRouteImport.update({
  id: '/thresholds',
  path: '/thresholds',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth_/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAlertsRoute = AuthenticatedAppAlertsRouteImport.update({
  id: '/app/alerts',
  path: '/app/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAssetsRoute = AuthenticatedAppAssetsRouteImport.update({
  id: '/app/assets',
  path: '/app/assets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppCopilotRoute = AuthenticatedAppCopilotRouteImport.update({
  id: '/app/copilot',
  path: '/app/copilot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppDeploymentRoute =
  AuthenticatedAppDeploymentRouteImport.update({
    id: '/app/deployment',
    path: '/app/deployment',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppEventsRoute = AuthenticatedAppEventsRouteImport.update({
  id: '/app/events',
  path: '/app/events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppMapRoute = AuthenticatedAppMapRouteImport.update({
  id: '/app/map',
  path: '/app/map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppPostureRoute = AuthenticatedAppPostureRouteImport.update({
  id: '/app/posture',
  path: '/app/posture',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRiskRoute = AuthenticatedAppRiskRouteImport.update({
  id: '/app/risk',
  path: '/app/risk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppThresholdsRoute =
  AuthenticatedAppThresholdsRouteImport.update({
    id: '/app/thresholds',
    path: '/app/thresholds',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppTimelineRoute =
  AuthenticatedAppTimelineRouteImport.update({
    id: '/app/timeline',
    path: '/app/timeline',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/assets': typeof AssetsRoute
  '/auth': typeof AuthRoute
  '/copilot': typeof CopilotRoute
  '/deployment': typeof DeploymentRoute
  '/events': typeof EventsRoute
  '/map': typeof MapRoute
  '/posture': typeof PostureRoute
  '/risk': typeof RiskRoute
  '/thresholds': typeof ThresholdsRoute
  '/timeline': typeof TimelineRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/alerts': typeof AuthenticatedAppAlertsRoute
  '/app/assets': typeof AuthenticatedAppAssetsRoute
  '/app/copilot': typeof AuthenticatedAppCopilotRoute
  '/app/deployment': typeof AuthenticatedAppDeploymentRoute
  '/app/events': typeof AuthenticatedAppEventsRoute
  '/app/map': typeof AuthenticatedAppMapRoute
  '/app/posture': typeof AuthenticatedAppPostureRoute
  '/app/risk': typeof AuthenticatedAppRiskRoute
  '/app/thresholds': typeof AuthenticatedAppThresholdsRoute
  '/app/timeline': typeof AuthenticatedAppTimelineRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/assets': typeof AssetsRoute
  '/auth': typeof AuthRoute
  '/copilot': typeof CopilotRoute
  '/deployment': typeof DeploymentRoute
  '/events': typeof EventsRoute
  '/map': typeof MapRoute
  '/posture': typeof PostureRoute
  '/risk': typeof RiskRoute
  '/thresholds': typeof ThresholdsRoute
  '/timeline': typeof TimelineRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/alerts': typeof AuthenticatedAppAlertsRoute
  '/app/assets': typeof AuthenticatedAppAssetsRoute
  '/app/copilot': typeof AuthenticatedAppCopilotRoute
  '/app/deployment': typeof AuthenticatedAppDeploymentRoute
  '/app/events': typeof AuthenticatedAppEventsRoute
  '/app/map': typeof AuthenticatedAppMapRoute
  '/app/posture': typeof AuthenticatedAppPostureRoute
  '/app/risk': typeof AuthenticatedAppRiskRoute
  '/app/thresholds': typeof AuthenticatedAppThresholdsRoute
  '/app/timeline': typeof AuthenticatedAppTimelineRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/alerts': typeof AlertsRoute
  '/assets': typeof AssetsRoute
  '/auth': typeof AuthRoute
  '/copilot': typeof CopilotRoute
  '/deployment': typeof DeploymentRoute
  '/events': typeof EventsRoute
  '/map': typeof MapRoute
  '/posture': typeof PostureRoute
  '/risk': typeof RiskRoute
  '/thresholds': typeof ThresholdsRoute
  '/timeline': typeof TimelineRoute
  '/auth_/callback': typeof AuthCallbackRoute
  '/_authenticated/app/alerts': typeof AuthenticatedAppAlertsRoute
  '/_authenticated/app/assets': typeof AuthenticatedAppAssetsRoute
  '/_authenticated/app/copilot': typeof AuthenticatedAppCopilotRoute
  '/_authenticated/app/deployment': typeof AuthenticatedAppDeploymentRoute
  '/_authenticated/app/events': typeof AuthenticatedAppEventsRoute
  '/_authenticated/app/map': typeof AuthenticatedAppMapRoute
  '/_authenticated/app/posture': typeof AuthenticatedAppPostureRoute
  '/_authenticated/app/risk': typeof AuthenticatedAppRiskRoute
  '/_authenticated/app/thresholds': typeof AuthenticatedAppThresholdsRoute
  '/_authenticated/app/timeline': typeof AuthenticatedAppTimelineRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/assets'
    | '/auth'
    | '/copilot'
    | '/deployment'
    | '/events'
    | '/map'
    | '/posture'
    | '/risk'
    | '/thresholds'
    | '/timeline'
    | '/auth/callback'
    | '/app/alerts'
    | '/app/assets'
    | '/app/copilot'
    | '/app/deployment'
    | '/app/events'
    | '/app/map'
    | '/app/posture'
    | '/app/risk'
    | '/app/thresholds'
    | '/app/timeline'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/assets'
    | '/auth'
    | '/copilot'
    | '/deployment'
    | '/events'
    | '/map'
    | '/posture'
    | '/risk'
    | '/thresholds'
    | '/timeline'
    | '/auth/callback'
    | '/app/alerts'
    | '/app/assets'
    | '/app/copilot'
    | '/app/deployment'
    | '/app/events'
    | '/app/map'
    | '/app/posture'
    | '/app/risk'
    | '/app/thresholds'
    | '/app/timeline'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/alerts'
    | '/assets'
    | '/auth'
    | '/copilot'
    | '/deployment'
    | '/events'
    | '/map'
    | '/posture'
    | '/risk'
    | '/thresholds'
    | '/timeline'
    | '/auth_/callback'
    | '/_authenticated/app/alerts'
    | '/_authenticated/app/assets'
    | '/_authenticated/app/copilot'
    | '/_authenticated/app/deployment'
    | '/_authenticated/app/events'
    | '/_authenticated/app/map'
    | '/_authenticated/app/posture'
    | '/_authenticated/app/risk'
    | '/_authenticated/app/thresholds'
    | '/_authenticated/app/timeline'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AlertsRoute: typeof AlertsRoute
  AssetsRoute: typeof AssetsRoute
  AuthRoute: typeof AuthRoute
  CopilotRoute: typeof CopilotRoute
  DeploymentRoute: typeof DeploymentRoute
  EventsRoute: typeof EventsRoute
  MapRoute: typeof MapRoute
  PostureRoute: typeof PostureRoute
  RiskRoute: typeof RiskRoute
  ThresholdsRoute: typeof ThresholdsRoute
  TimelineRoute: typeof TimelineRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployment': {
      id: '/deployment'
      path: '/deployment'
      fullPath: '/deployment'
      preLoaderRoute: typeof DeploymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posture': {
      id: '/posture'
      path: '/posture'
      fullPath: '/posture'
      preLoaderRoute: typeof PostureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thresholds': {
      id: '/thresholds'
      path: '/thresholds'
      fullPath: '/thresholds'
      preLoaderRoute: typeof ThresholdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/callback': {
      id: '/auth_/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/alerts': {
      id: '/_authenticated/app/alerts'
      path: '/app/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AuthenticatedAppAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/assets': {
      id: '/_authenticated/app/assets'
      path: '/app/assets'
      fullPath: '/app/assets'
      preLoaderRoute: typeof AuthenticatedAppAssetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/copilot': {
      id: '/_authenticated/app/copilot'
      path: '/app/copilot'
      fullPath: '/app/copilot'
      preLoaderRoute: typeof AuthenticatedAppCopilotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/deployment': {
      id: '/_authenticated/app/deployment'
      path: '/app/deployment'
      fullPath: '/app/deployment'
      preLoaderRoute: typeof AuthenticatedAppDeploymentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/events': {
      id: '/_authenticated/app/events'
      path: '/app/events'
      fullPath: '/app/events'
      preLoaderRoute: typeof AuthenticatedAppEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/map': {
      id: '/_authenticated/app/map'
      path: '/app/map'
      fullPath: '/app/map'
      preLoaderRoute: typeof AuthenticatedAppMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/posture': {
      id: '/_authenticated/app/posture'
      path: '/app/posture'
      fullPath: '/app/posture'
      preLoaderRoute: typeof AuthenticatedAppPostureRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/risk': {
      id: '/_authenticated/app/risk'
      path: '/app/risk'
      fullPath: '/app/risk'
      preLoaderRoute: typeof AuthenticatedAppRiskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/thresholds': {
      id: '/_authenticated/app/thresholds'
      path: '/app/thresholds'
      fullPath: '/app/thresholds'
      preLoaderRoute: typeof AuthenticatedAppThresholdsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/timeline': {
      id: '/_authenticated/app/timeline'
      path: '/app/timeline'
      fullPath: '/app/timeline'
      preLoaderRoute: typeof AuthenticatedAppTimelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppAlertsRoute: typeof AuthenticatedAppAlertsRoute
  AuthenticatedAppAssetsRoute: typeof AuthenticatedAppAssetsRoute
  AuthenticatedAppCopilotRoute: typeof AuthenticatedAppCopilotRoute
  AuthenticatedAppDeploymentRoute: typeof AuthenticatedAppDeploymentRoute
  AuthenticatedAppEventsRoute: typeof AuthenticatedAppEventsRoute
  AuthenticatedAppMapRoute: typeof AuthenticatedAppMapRoute
  AuthenticatedAppPostureRoute: typeof AuthenticatedAppPostureRoute
  AuthenticatedAppRiskRoute: typeof AuthenticatedAppRiskRoute
  AuthenticatedAppThresholdsRoute: typeof AuthenticatedAppThresholdsRoute
  AuthenticatedAppTimelineRoute: typeof AuthenticatedAppTimelineRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppAlertsRoute: AuthenticatedAppAlertsRoute,
  AuthenticatedAppAssetsRoute: AuthenticatedAppAssetsRoute,
  AuthenticatedAppCopilotRoute: AuthenticatedAppCopilotRoute,
  AuthenticatedAppDeploymentRoute: AuthenticatedAppDeploymentRoute,
  AuthenticatedAppEventsRoute: AuthenticatedAppEventsRoute,
  AuthenticatedAppMapRoute: AuthenticatedAppMapRoute,
  AuthenticatedAppPostureRoute: AuthenticatedAppPostureRoute,
  AuthenticatedAppRiskRoute: AuthenticatedAppRiskRoute,
  AuthenticatedAppThresholdsRoute: AuthenticatedAppThresholdsRoute,
  AuthenticatedAppTimelineRoute: AuthenticatedAppTimelineRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AlertsRoute: AlertsRoute,
  AssetsRoute: AssetsRoute,
  AuthRoute: AuthRoute,
  CopilotRoute: CopilotRoute,
  DeploymentRoute: DeploymentRoute,
  EventsRoute: EventsRoute,
  MapRoute: MapRoute,
  PostureRoute: PostureRoute,
  RiskRoute: RiskRoute,
  ThresholdsRoute: ThresholdsRoute,
  TimelineRoute: TimelineRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
