using System.Text.Json.Serialization;

namespace PIFabricForwarder.Models;

public enum TagMode
{
    Channel,
    Poll,
    Skip
}

/// <summary>
/// One row in tags.json. Generated by a bootstrap script and consumed by the
/// HotPath / PollPath loops to decide how to read each tag.
/// </summary>
public sealed class PiTagConfig
{
    [JsonPropertyName("tag")]   public string Tag { get; set; } = "";
    [JsonPropertyName("webId")] public string WebId { get; set; } = "";
    [JsonPropertyName("plant")] public string Plant { get; set; } = "";
    [JsonPropertyName("mode")]
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public TagMode Mode { get; set; } = TagMode.Channel;
}
